#!/bin/bash
# rbx install instructions: https://github.com/postmodern/chruby/wiki/Rubinius

apt-get -y --force-yes install lsb-release
echo deb http://archive.ubuntu.com/ubuntu $(lsb_release -cs) main universe > /etc/apt/sources.list.d/universe.list
apt-get -q update

apt-get -y --force-yes install \
  build-essential \
  git \
  curl \
  bison \
  ruby-dev \
  zlib1g-dev \
  libyaml-dev \
  libssl-dev \
  libreadline-dev \
  libncurses5-dev

export PATH=/usr/local/ruby/bin:$PATH
/usr/local/ruby/bin/gem update --system

cd /usr/local/src
wget --quiet http://releases.rubini.us/rubinius-2.2.6.tar.bz2
tar jxf rubinius-2.2.6.tar.bz2
cd /usr/local/src/rubinius-2.2.6
curl -fsSL curl.haxx.se/ca/cacert.pem -o /usr/local/src/rubinius-2.2.6/lib/rubygems/ssl_certs/cert.pem

/usr/local/ruby/bin/bundle

./configure --prefix=/usr/local/rubinius --libc=/usr/lib/x86_64-linux-gnu/libc
/usr/local/ruby/bin/rake install
rm /usr/local/src/rubinius-2.2.6.tar.bz2

locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
echo "export LC_ALL=en_US.UTF-8" >> /etc/environment
/usr/local/rubinius/bin/gem install bundler
