#!/bin/bash

apt-get -y --force-yes install \
  build-essential \
  git \
  curl \
  bison \
  ruby-dev \
  zlib1g-dev \
  libyaml-dev \
  libssl-dev \
  libreadline-dev \
  libncurses5-dev

export PATH=/usr/local/ruby/bin:$PATH
/usr/local/ruby/bin/gem update --system

cd /usr/local/src
wget --quiet http://releases.rubini.us/rubinius-2.2.3.tar.bz2
tar jxf rubinius-2.2.3.tar.bz2
cd /usr/local/src/rubinius-2.2.3
curl -fsSL curl.haxx.se/ca/cacert.pem -o /usr/local/src/rubinius-2.2.3/lib/rubygems/ssl_certs/cert.pem
/usr/local/ruby/bin/bundle
./configure --prefix=/usr/local/rubinius
/usr/local/ruby/bin/rake install
rm /usr/local/src/rubinius-2.2.3.tar.bz2

locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
echo "export LC_ALL=en_US.UTF-8" >> /etc/environment
/usr/local/rubinius/bin/gem install bundler
/usr/local/rubinius/bin/gem install rubysl-tracer
